concurrent = 1
check_interval = 0

[[runners]]
  name = "local-sbt"
  url = "https://gitlab.bgoner.com/ci"
  token = "8c60e2c19fee71ffdf3812eff2d476"
  executor = "shell"
  [runners.ssh]
  [runners.docker]
    tls_verify = false
    image = ""
    privileged = false
    disable_cache = false
  [runners.parallels]
    base_name = ""
    disable_snapshots = false
  [runners.virtualbox]
    base_name = ""
    disable_snapshots = false
  [runners.cache]

