version: '2'
services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:latest
    command: elasticsearch -Des.network.host=0.0.0.0
    volumes:
      - /srv/elasticsearch:/usr/share/elasticsearch/data
  logstash:
    container_name: logstash
    build: logstash/
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    ports:
      - "5000:5000"
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
    links:
      - elasticsearch
  kibana:
    container_name: kibana
    build: kibana/
    volumes:
      - ./kibana/config/:/opt/kibana/config/
    links:
      - elasticsearch
  influxdb:
    container_name: influxdb
    image: influxdb:latest
    env_file:
      - 'env.influxdb'
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    volumes:
      - /srv/influxdb:/var/lib/influxdb
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    volumes:
      - /srv/grafana:/var/lib/grafana
    links:
      - influxdb
  gitlab:
    container_name: gitlab
    build: gitlab/
    restart: always
    hostname: 'localhost'
    ports:
      - "2201:22"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.bgoner.com'
        registry_external_ur 'https://registry.gitlab.bgoner.com'
        gitlab_rails['gitlab_shell_ssh_port'] = 2201
    extra_hosts:
     - "gitlab.bgoner.com:127.0.0.1"
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/srv/gitlab/config:/etc/gitlab'
      - '/srv/gitlab/logs:/var/log/gitlab'
      - '/srv/gitlab/data:/var/opt/gitlab'
      - './gitlab/gitlab.crt:/etc/gitlab/ssl/localhost.crt'
      - './gitlab/gitlab.key:/etc/gitlab/ssl/localhost.key'
      - './gitlab/gitlab.crt:/etc/gitlab/ssl/80.72.68.14.crt'
      - './gitlab/gitlab.key:/etc/gitlab/ssl/80.72.68.14.key'
      - './gitlab/gitlab.crt:/etc/gitlab/ssl/gitlab.bgoner.com.crt'
      - './gitlab/gitlab.key:/etc/gitlab/ssl/gitlab.bgoner.com.key'
      - './gitlab/gitlab.crt:/etc/gitlab/ssl/registry.gitlab.bgoner.com.crt'
      - './gitlab/gitlab.key:/etc/gitlab/ssl/registry.gitlab.bgoner.com.key'
  gitlab_runner:
    container_name: gitlab_runner
    build: gitlab_runner
    restart: always
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './gitlab/gitlab.crt:/etc/gitlab-runner/certs/gitlab.bgoner.com.crt'
      - './gitlab/gitlab.crt:/etc/gitlab-runner/certs/80.72.68.14.crt'
    links:
      - "gitlab:gitlab.bgoner.com"
  nginx:
    container_name: nginx
    build: nginx/
    ports:
      - "443:443"
    links:
      - kibana
      - grafana
      - gitlab
